name: Build EchoScript

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-macos:

    runs-on: macos-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS
        run: |
          pyinstaller \
            EchoScript.spec \
            --noconfirm \
            --clean

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: EchoScript-macOS
          path: dist/

  build-windows:

    runs-on: windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows
        run: |
          pyinstaller `
            --name EchoScript `
            --windowed `
            --icon assets/icon.ico `
            --noconfirm `
            --clean `
            app.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: EchoScript-Windows
          path: dist/